name: soft_creative_app
description: Soft Creative home service booking app (Electrician, Plumber, AC Repair, etc.)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add image files under assets/images/.
  assets:
    - assets/images/
    - assets/images_onboardingscreen/
    - assets/clientdashbord_icon/
    - assets/technician_icon/
    - assets/admin_icon/
    - assets/service_detail_banner/

  generate: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/KantumruyPro-Light.ttf
          weight: 300
        - asset: assets/fonts/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KantumruyPro-Bold.ttf
          weight: 700
